name: Scraper por Rango de Páginas

on:
  workflow_dispatch:
    inputs:
      category_url:
        description: 'URL de la categoría (Ej: https://missav.ws/dm628/en/uncensored-leak)'
        required: true
        default: 'https://missav.ws/dm628/en/uncensored-leak'
      start_page:
        description: 'Página Inicial (Número)'
        required: true
        default: '1'
      end_page:
        description: 'Página Final (Número)'
        required: true
        default: '5'

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write 

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar dependencias
      run: |
        pip install requests beautifulsoup4

    - name: Ejecutar Scraper de Páginas
      env:
        CATEGORY_URL: ${{ github.event.inputs.category_url }}
        START_PAGE: ${{ github.event.inputs.start_page }}
        END_PAGE: ${{ github.event.inputs.end_page }}
      run: python scraper_paginas.py

    - name: Guardar cambios
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Playlist páginas ${{ github.event.inputs.start_page }}-${{ github.event.inputs.end_page }}"
        file_pattern: "playlists/*.m3u"
