name: Scraper por Rango de Paginas

on:
  workflow_dispatch:
    inputs:
      category_url:
        description: 'URL Categoria'
        required: true
        default: 'https://missav.ws/dm628/en/uncensored-leak'
      start_page:
        description: 'Pagina Inicial'
        required: true
        default: '1'
      end_page:
        description: 'Pagina Final'
        required: true
        default: '2'

jobs:
  scrape-job:
    runs-on: ubuntu-22.04
    
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Scraper
        env:
          CATEGORY_URL: ${{ inputs.category_url }}
          START_PAGE: ${{ inputs.start_page }}
          END_PAGE: ${{ inputs.end_page }}
        run: python scraper_paginas.py

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add playlist p${{ inputs.start_page }}-p${{ inputs.end_page }}"
          file_pattern: "playlists/*.m3u"
